services:
  frontend:
    container_name: taskmanager-frontend
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    ports:
      - 8980:8000
    command: ["npm", "start"]
  
  backend:
    container_name: taskmanager-backend
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "8990:8000"
    command: ["python", "main.py"]