name: Workflow for React App with FastAPI backend

on:
 push:
   branches: [main]
 workflow_dispatch:
 
jobs:
  checkout_code_verify_lint:
    runs-on:
      - self-hosted
    steps:
      - name: Checkout Repo "taskManager"
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
 
      - name: Run one line script show last commit
        run: git log -1 
         
      - name: Super-linter
        uses: super-linter/super-linter@v6.4.1  # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
